version: '3.8'

services:
  nanobit-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanobit-portfolio
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL:-file:./dev.db}
    volumes:
      - nanobit-db:/app/prisma

volumes:
  nanobit-db:
    name: nanobit_db_data
