version: '3.8'

services:
  nanobit-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanobit-portfolio
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL:-file:./dev.db}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - nanobit-db:/app/prisma
      - nanobit-uploads:/app/public/uploads

volumes:
  nanobit-db:
    name: nanobit_db_data
  nanobit-uploads:
    name: nanobit_uploads_data
